### ISSUE TITLE
Nova Partida: Datepicker traz a data, mas ela fica como Invalid date na listagem

### ISSUE THREAD

**Issue by thiagobfiorenza** [SocialBoardGames/socialgames#68]
Se eu clico na data, em vez de digitá-la, ela não está sendo salva, ou está sendo salva em um formato errado.

**Comment by psico** [comment]
Ouve um erro no cadastro de Matches no cadastro de data no passado, nos novos registros isso não deve acontecer.

**Comment by andrexbass** [comment]
done!
