### ISSUE TITLE
Matches: Ter uma data unificada para o momento que a partida de fato aconteceu

### ISSUE THREAD

**Issue by psico** [SocialBoardGames/socialgames#69]
Matches: Ter uma data unificada para o momento que a partida de fato aconteceu`.

Atualmente existem problemas na ordenação das partidas pois existe o create_at e a data de agendamento, quando é para ordenar por data não é possível pois são campos diferentes

**Comment by andrexbass** [comment]
Segue a seguinte lógica: se houver data de agendamento se usa ela, caso não exista considera a created_at

**Comment by andrexbass** [comment]
Segue a seguinte lógica: se houver data de agendamento se usa ela, caso não exista considera a created_at

**Comment by andrexbass** [comment]
Foi criado o campo finish_at que eh gravado quando uma partida é finalizada.
